import Link from 'next/link';
import { Panel, SectionTitle, Badge } from '@/components/ui';
import { ChineseText } from '@/components/ChineseText';
import { ESCALATION_LADDER } from '@/data/glossary.zh';
import { SOURCES } from '@/data/sources';
import { BEATS, LOCALES, DIRECT_FEEDS } from '@/data/feeds';
import { FREE_LIMIT, METERED } from '@/lib/quota';
import { ROSTER_REVIEWED } from '@/data/people';
import { TREND_SERIES_DAYS } from '@/lib/risk';

export const metadata = { title: 'Methodology' };

function H({ children }: { children: React.ReactNode }) {
  return <h2 className="mt-9 mb-2.5 text-[17px] font-semibold tracking-tight text-text">{children}</h2>;
}
function P({ children }: { children: React.ReactNode }) {
  return <p className="mb-3 max-w-3xl text-[13.5px] leading-relaxed text-muted">{children}</p>;
}

export default function MethodologyPage() {
  const ownership = SOURCES.reduce((m, s) => m.set(s.ownership, (m.get(s.ownership) ?? 0) + 1), new Map<string, number>());
  const queries = BEATS.reduce((n, b) => n + b.queries.length, 0);

  return (
    <div className="max-w-4xl">
      <div className="text-[10px] uppercase tracking-[0.22em] text-faint">Methodology</div>
      <h1 className="mt-1 text-2xl font-semibold tracking-tight">How this engine works, and where it fails</h1>
      <P>
        Every number on this site is computed from rules written down here. Nothing is a black box,
        and nothing is generated by a model guessing at plausibility. If you disagree with a score,
        you should be able to find the exact arithmetic that produced it and argue with it.
      </P>

      <Panel className="my-6 border-l-2 border-l-[color:var(--color-accent)] p-4">
        <div className="text-[11px] uppercase tracking-[0.16em] text-[color:var(--color-accent)]">The central caveat</div>
        <p className="mt-2 text-[13.5px] leading-relaxed text-text">
          This engine measures <strong>corroboration and provenance</strong>. It does not, and cannot,
          determine truth. A claim repeated by many independent outlets scores highly whether or not it
          is correct; a correct exclusive scores low because it is, by definition, uncorroborated.
          Corroboration scores tell you how well-attested a report is — treat them as a research aid,
          never as a verdict.
        </p>
      </Panel>

      <H>1. Ingestion</H>
      <P>
        The engine pulls from {DIRECT_FEEDS.length} direct publisher and institutional feeds, plus{' '}
        {queries} aggregator queries spread across {Object.keys(LOCALES).length} language-region locales.
        Each watched relationship is queried <em>in the languages of the parties to it</em>: an
        India–China border incident is fetched in English, Hindi and Simplified Chinese separately,
        so the PRC framing arrives alongside the Indian one rather than filtered through it.
      </P>
      <P>
        Feeds are validated for actual feed content, not HTTP status. Several government endpoints —
        including the PRC Ministry of Foreign Affairs and mod.gov.cn — advertise RSS but return HTML
        or maintenance pages, so they are deliberately excluded. PRC official statements are reached
        through Chinese-locale aggregator queries instead, which means coverage of PRC domestic media
        is <strong>partial and second-hand</strong>. Absence of a signal here is not absence of an event.
      </P>

      <H>2. Source registry and ownership</H>
      <P>
        {SOURCES.length} outlet groups are hand-classified by country, language and ownership.
        Ownership is the load-bearing field in the whole system, because it encodes the difference
        between five sources and one source repeated five times. The registry was extended from the
        outlets actually appearing in ingested data, not assembled from a list of famous mastheads.
      </P>
      <div className="my-4 flex flex-wrap gap-2">
        {[...ownership.entries()].map(([k, n]) => (
          <Badge key={k} tone="var(--color-muted)">{k.replace('_', ' ')} — {n}</Badge>
        ))}
      </div>
      <P>
        Unrecognised outlets are assigned the <em>weakest</em> reliability tier and no country.
        Unknown is not treated as neutral, because an unfamiliar domain is more often a content
        farm than a newspaper of record — and an unplaced outlet never counts toward the
        source-country spread, so unrecognised sources cannot manufacture geographic diversity.
      </P>
      <P>
        Think tanks and research institutes are classed <em>analysis</em> and deliberately excluded
        from corroboration counts. A CSIS or ORF paper is commentary on an event, not an independent
        witness to it; treating it as a second source would double-count a single underlying report.
        Such items are still shown in the evidence list, labelled.
      </P>
      <P>
        Chinese commercial portals — Sohu, NetEase, Sina, Tencent, Phoenix — are privately owned
        but operate under content-licensing and censorship obligations, so they are classed
        state-affiliated rather than independent. This is a judgement call, and it is made
        explicit here rather than buried in a weight.
      </P>

      <H>3. The Chinese-language layer</H>
      <P>
        Chinese text is matched against a curated geopolitical glossary, longest-term-first, with each
        term counted once per article — an outlet repeating a word six times has made one editorial
        choice, not six. Terms are categorised, and those marked <em>framing</em> are treated as
        signals in themselves: an outlet writing 藏南 rather than a neutral name for Arunachal Pradesh
        has taken a sovereignty position in the act of naming.
      </P>
      <P>
        Every Chinese headline on the site also carries its romanisation and a word-by-word English
        gloss, so a reader without Chinese can still say a name aloud and get the gist. Pinyin is
        generated deterministically; the gloss is a dictionary lookup, not a translation, and is
        labelled <em>Glossed</em> wherever it appears. It has no grammar and will read as a list of
        senses rather than as prose. Where an event has been analysed by the optional language model,
        a real sentence translation replaces it. Dictionary data is{' '}
        <a href="https://www.mdbg.net/chinese/dictionary?page=cc-cedict" target="_blank"
          rel="noopener noreferrer" className="underline hover:text-muted">CC-CEDICT</a>, used under{' '}
        <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank"
          rel="noopener noreferrer" className="underline hover:text-muted">CC BY-SA 4.0</a>.
      </P>
      <P>
        Separately, text is matched against the PRC official escalation ladder — {ESCALATION_LADDER.length} set-piece
        formulae that Beijing moves along deliberately. Matching is longest-first because the formulae
        nest: rung 4 contains rung 3 as a substring, and matching the shorter form would systematically
        understate the stated position.
      </P>
      <Panel className="my-4 p-4">
        <div className="space-y-1">
          {ESCALATION_LADDER.map((r) => (
            <div key={r.rung} className="flex items-baseline gap-3 text-[12px]">
              <span className="mono-num w-5 text-right text-faint">{r.rung}</span>
              <span className="w-40 flex-none">
                <ChineseText text={r.zh} size="small" accent clamp={false} />
              </span>
              <span className="w-52 flex-none text-muted">{r.en}</span>
              <span className="mono-num text-[10.5px] text-faint">sev {r.severity}</span>
            </div>
          ))}
        </div>
      </Panel>
      <P>
        The top rung is rare and historically weighty: it was carried by People&apos;s Daily before the
        1962 war with India and the 1979 war with Vietnam. It is included because its absence from
        English-language monitoring is a real gap — but the historical sample is tiny, and it is
        evidence, not prophecy. Verify the outlet and date directly before acting on any detection.
      </P>

      <H>4. Clustering into events</H>
      <P>
        Reports are grouped by an inverted index over title tokens, glossed English terms, flashpoint
        tags and Chinese character bigrams, then merged with union-find. Two reports join the same
        event only if they share at least one actor, fall in the same domain, and land within a
        60-hour window. The glossed English terms are what allow a Chinese and an English report of
        one event to merge at all, since they share no surface tokens.
      </P>

      <H>5. The corroboration score</H>
      <P>Each event scores out of 100 across six positive signals and one penalty:</P>
      <Panel className="my-4 divide-y divide-[color:var(--color-line-soft)] p-4">
        {[
          ['Independent outlets', '25', 'Distinct commercial or public-broadcaster outlets. State, state-affiliated, tabloid and think-tank sources are all excluded from this count — it is the strongest single signal, so it is kept strict.'],
          ['Ownership diversity', '20', 'Presence of independent reporting, plus a mix of ownership classes.'],
          ['Source-country spread', '20', 'Distinct countries of publication. One state’s press is one perspective.'],
          ['Language spread', '10', 'Distinct languages. Cross-language pickup is hard to manufacture.'],
          ['Primary source', '15', 'A ministry, military or official spokesperson statement is present.'],
          ['Outlet track record', '10', 'Reliability tier of the strongest outlet in the cluster.'],
          ['Contradiction penalty', '−10', 'Sources in the cluster assert and deny the same claim.'],
        ].map(([label, max, detail]) => (
          <div key={label} className="flex gap-4 py-2.5">
            <span className="mono-num w-10 flex-none text-right text-[12px] text-[color:var(--color-accent)]">{max}</span>
            <div>
              <div className="text-[12.5px] text-text">{label}</div>
              <div className="text-[11.5px] leading-snug text-muted">{detail}</div>
            </div>
          </div>
        ))}
      </Panel>
      <P>
        Band labels are deliberately about reporting depth rather than veracity: &ldquo;Single report&rdquo;
        describes corroboration, where &ldquo;unverified&rdquo; would imply a judgement on the claim.
      </P>

      <H>6. Risk and tension indices</H>
      <P>
        An event&apos;s contribution to risk is its escalation score, gated by its corroboration score,
        decayed with a 14-day half-life. Confidence-gating is deliberate: a dramatic single-source
        claim should barely move an index. Country risk sums contributions across six vectors —
        Military, Economic, Cyber, Internal, Diplomatic, Energy — then applies a saturating curve,
        so the difference between 0 and 5 incidents matters more than between 20 and 30. Dyad tension
        uses the same maths restricted to events naming both states.
      </P>

      <H>7. The network of states</H>
      <P>
        The threat board reads one state or one pair at a time. The network view reads the
        shape they sit in: every state that has shared a clustered event with another is a
        node, and the line between two of them is the friction across all the events they
        appear in together.
      </P>
      <P>
        An edge therefore means the two states appeared in the same clustered event. That is a
        <strong className="text-text"> reporting relationship, not a diplomatic one</strong> — two
        states named in one article are not necessarily interacting, and the engine does not
        claim otherwise. Friction reuses <span className="mono-num">impact()</span>, the same
        function behind the dyad tension scores, so a line here and a tension score there are the
        same arithmetic over the same events rather than two independent estimates. They can
        still differ by a point: each page decays its events to the moment it is rendered, so
        a pair sitting on a rounding boundary may read 57 here and 56 there.
      </P>
      <P>
        Dashed lines are the de-escalatory signal. They apply the same confidence gate and
        recency decay to the negative half of the escalation scale — the half the risk index
        discards outright. Across the corpus that rests on
        <strong className="text-text"> roughly 2% of events</strong>, which is far too thin to
        carry a score. It is drawn as an overlay, labelled with the count behind it, and it has
        no measure of its own. It is not a map of alliances.
      </P>
      <P>
        Eight measures sit beside the drawing: Connections, Total friction, Brokerage, Contagion
        exposure, Reach, Entanglement, Core depth and Conflict cluster. Every one of them is
        computed on the <strong className="text-text">full network, never on the neighbourhood
        being drawn</strong>. A drilldown caps its fan-out for legibility — the busiest state in
        the corpus has 59 connections, which is a hairball on the first click — but that cap is a
        drawing decision and nothing is ranked against it. The denominator in every rank is
        the whole network, however few states are drawn.
      </P>
      <P>
        Distance is the reciprocal of friction: a strong tie makes two states close, so the
        shortest path between two states runs through their fiercest disputes rather than
        around them. Conflict clusters group states most embroiled
        <strong className="text-text"> with each other</strong>. They are mutual antagonists —
        not blocs, alliances or alignments, and reading them as sides is the one mistake this
        view most invites.
      </P>
      <P>
        Every measure is as-of-now over the {TREND_SERIES_DAYS}-day retention window, not a historical
        series. A state that was central last quarter and quiet since will read as quiet.
      </P>

      <H>8. People in the network</H>
      <P>
        The same graph, with officials as nodes. A person is linked to a state when the two
        were named in the same clustered event — a <strong className="text-text">reporting
        relationship, not an action</strong>. The engine cannot tell an official visiting a
        state from one being condemned by it, and does not pretend to.
      </P>
      <P>
        Coverage is exactly the roster: a hand-written list of senior figures with the forms
        outlets actually print in their own languages, last reviewed{' '}
        <span className="mono-num">{ROSTER_REVIEWED}</span>. An official who is not listed is
        invisible here, so an <strong className="text-text">absence is never evidence</strong>{' '}
        that someone was uninvolved — it is as likely to mean the roster has gone stale since
        a cabinet changed. Nothing on this layer is extracted by a model; the roster is
        curated for the same reason every other weight on this page is written down.
      </P>
      <P>
        Two officials are linked when they were named in the same clustered event. That is a
        weaker claim than it looks, and it is worth stating plainly because a line drawn
        between two people reads as a relationship in a way a line between two countries does
        not: <strong className="text-text">a co-mention is not an interaction</strong>. No edge
        on this view carries an action, and the reason is not squeamishness — it is that the
        corpus cannot support one. A headline reading{' '}
        <em>&ldquo;Zelensky warns airlines Russian skies not safe&rdquo;</em> names both
        Zelensky and, in its summary, Putin, so the two appear on one line here. Zelensky
        warned airlines. The two did not speak. Labelling that edge from its verb would have
        this page assert <em>Zelensky warned Putin</em> — not a thin signal but a confidently
        wrong one. Resolving a verb to its object needs the sentence, and this pipeline stores
        headlines.
      </P>
      <P>
        The states shown on an edge are where the reporting was{' '}
        <strong className="text-text">set, not where the people were</strong>. Two officials
        named in a story about the South China Sea need not have been anywhere near it. They
        are accumulated across every event behind the edge rather than sampled from the
        strongest few, and the three most frequent are shown with the remainder counted.
      </P>
      <P>
        This layer is thin beside the state graph, and that is worth knowing before reading
        much into it: person-to-person ties rest on the small share of events naming two or
        more listed officials, against several thousand events overall. The thin-evidence
        caveat that applies to any low-degree node applies here throughout.
      </P>
      <P>
        A person&apos;s tie to their own state is drawn but left out of the friction total,
        which is why that row reads <em>Cross-border friction</em>. A leader is named beside
        their own country in nearly every story about it, so counting it would turn the figure
        into a ranking of who governs a busy country. The structural ranks keep the tie: those
        are positions in the real network, and dropping a genuine connection to compute them
        would rank people in a graph that does not exist.
      </P>
      <P>
        Two measures from the state network are missing here rather than forgotten. A
        person-to-state graph has no triangles at all, so <em>Entanglement</em> — which counts
        how many of a node&apos;s counterparts are joined to each other — is exactly zero for
        everyone, and <em>Conflict cluster</em> would group people together with countries,
        which says nothing.
      </P>
      <P>
        This layer is thin, and thinner than the state network by an order of magnitude.
        Roughly one article in ten names a listed official at all. There are also no
        person-to-person links: people are named in the body of an article, and this engine
        stores headlines, so only about 1% of articles name two figures — far too few to draw
        a network from. That is a limit of the corpus rather than of the method, and it would
        take storing full article text to lift.
      </P>

      <H>9. The optional language-model layer</H>
      <P>
        Everything above is deterministic: rules, lexicons and arithmetic, with no external
        service involved. One feature sits outside that boundary. On an event page, if the
        deployment has an API key configured, you can ask a language model to read the
        cluster&apos;s reports in their own languages and set out how each bloc frames the same
        event, what the sources agree on, what they contest, and what evidence would settle it.
      </P>
      <P>
        It is constrained deliberately. The model is instructed to ground every statement in
        the supplied material, to add nothing from its own knowledge, to say plainly when the
        material is too thin, and never to assert that a claim is true or false. Article text
        is treated as untrusted third-party data, not as instructions. Results are cached per
        model, event and article set, so two readers of one event see the same analysis and the
        second costs nothing.
      </P>
      <P>
        If no key is configured, the panel says so and nothing else changes. No score, index or
        flag anywhere on this site is produced by a language model.
      </P>

      <H>10. Export</H>
      <P>
        Any event&apos;s full source table, or any filtered slice of the event corpus, exports as
        CSV or JSON. CSV carries a UTF-8 byte-order mark so spreadsheets render Chinese, Hindi
        and Arabic headlines correctly rather than as mojibake. Exports count as one metered
        analysis. Every JSON export embeds the corroboration disclaimer, so the caveat travels
        with the data.
      </P>

      <H>11. Free and paid</H>
      <P>
        Browsing, filtering, search, the live feed and this page are free and unmetered. {FREE_LIMIT} free
        analyses cover the deep views: {Object.values(METERED).join('; ').toLowerCase()}. Re-opening
        something already viewed never costs another credit.
      </P>
      <P>
        Signed-out visitors are metered by a device cookie, which is trivially cleared. That is stated
        here rather than hidden: only account-bound metering is real enforcement.
      </P>
      <P>
        The network view is priced per <em>walk</em> rather than per state. A credit is spent
        where a walk begins, and every state you then step to is free however far the walk
        runs; coming back later and starting again somewhere else spends another. Appending a
        walk to a link you were sent works the same way, which means the pricing can be
        sidestepped by anyone who edits the address bar — the same softness as the device
        cookie above, and stated for the same reason.
      </P>

      <H>12. Known limitations</H>
      <ol className="mb-3 max-w-3xl list-decimal space-y-2 pl-5 text-[13.5px] leading-relaxed text-muted">
        <li><strong className="text-text">Corroboration is not truth.</strong> Widely-repeated false claims score well. Ownership and country diversity are a partial mitigation, not a cure.</li>
        <li><strong className="text-text">PRC domestic coverage is partial.</strong> Ministry feeds are unavailable; Chinese material arrives via aggregator queries, which under-represent domestic-only outlets.</li>
        <li><strong className="text-text">Lexicon scoring is shallow.</strong> Keyword weights do not understand negation, sarcasm or hypotheticals. &ldquo;Rules out invasion&rdquo; scores as escalatory.</li>
        <li><strong className="text-text">The ladder has a small sample.</strong> The top rung has been used a handful of times in seventy years. Treat detections as prompts to investigate.</li>
        <li><strong className="text-text">Entity extraction is alias-based.</strong> An unlisted alias means a missed actor; a shared name means a false one.</li>
        <li><strong className="text-text">Absence is not evidence.</strong> The engine reports what its configured beats surface. Nothing here is a comprehensive picture of world events.</li>
        <li><strong className="text-text">Redistribution terms.</strong> Publisher and aggregator terms of service govern commercial use of this material. Review them before charging subscribers.</li>
      </ol>

      <div className="mt-8 flex gap-3">
        <Link href="/" className="text-[12px] text-muted hover:text-[color:var(--color-accent)]">← Threat board</Link>
        <Link href="/pricing" className="text-[12px] text-muted hover:text-[color:var(--color-accent)]">Plans →</Link>
      </div>
    </div>
  );
}
