// Generated by `npm run demo:capture` on 2026-09-20. Do not edit by hand.
// Real examples captured from the corpus, used by the demo tour when a live one is missing.
import type { Fallbacks } from '@/lib/demo/types';

export const FALLBACKS: Fallbacks = {
  "capturedOn": "2026-09-20",
  "language": {
    "headline": "Anthropic发布154页人工智能滥用报告含多领域涉华案例 北京：坚决反对攻击抹黑",
    "outlet": "RFI",
    "date": "2026-09-11",
    "rung": 6,
    "ladderZh": "坚决反对",
    "ladderEn": "resolute opposition"
  },
  "event": {
    "title": "Bae, Kim & Lee and Reed Smith host Korea-US seminar on chip export controls - CHOSUNBIZ",
    "confidence": 90,
    "signals": [
      {
        "key": "outlets",
        "label": "Independent outlets",
        "points": 25,
        "max": 25,
        "detail": "4 independent outlets of 6 reporting. 1 outlet reprinted a report already counted."
      },
      {
        "key": "ownership",
        "label": "Ownership diversity",
        "points": 20,
        "max": 20,
        "detail": "3 ownership class(es): independent, public, state."
      },
      {
        "key": "countries",
        "label": "Source-country spread",
        "points": 20,
        "max": 20,
        "detail": "4 country/countries of publication: HKG, TWN, KOR, PAK, plus 1 unrecognised outlet."
      },
      {
        "key": "languages",
        "label": "Language spread",
        "points": 0,
        "max": 10,
        "detail": "1 language(s): en."
      },
      {
        "key": "primary",
        "label": "Primary source",
        "points": 15,
        "max": 15,
        "detail": "Official statement present: APP / The Nation."
      },
      {
        "key": "tier",
        "label": "Outlet track record",
        "points": 10,
        "max": 10,
        "detail": "Strongest outlet in cluster is tier 1."
      }
    ],
    "flags": [
      "primary_sourced"
    ],
    "reports": [
      {
        "title": "U.S. Export Controls on Chinese Memory Chips Could Make or Break CRAM in 2026",
        "outlet": "24/7 Wall St."
      },
      {
        "title": "Opinion | Why more export controls won’t stop China’s industrial engine",
        "outlet": "South China Morning Post"
      },
      {
        "title": "CNAS Insights | America Must Expand AI Export Controls Amid Talks with China",
        "outlet": "CNA Taiwan"
      },
      {
        "title": "Bae, Kim & Lee and Reed Smith host Korea-US seminar on chip export controls - CHOSUNBIZ",
        "outlet": "Korean press"
      }
    ],
    "reprints": [
      {
        "title": "U.S. Export Controls on Chinese Memory Chips Could Make or Break CRAM in 2026",
        "outlet": "AOL.com"
      }
    ]
  },
  "ladder": {
    "rung": 6,
    "ladderZh": "坚决反对",
    "ladderEn": "resolute opposition",
    "beijing": {
      "title": "Anthropic发布154页人工智能滥用报告含多领域涉华案例 北京：坚决反对攻击抹黑",
      "outlet": "RFI",
      "date": "2026-09-11"
    },
    "other": {
      "title": "印度一军舰与巴基斯坦军舰相撞，巴基斯坦向印度提出强烈抗议 双方各执一词",
      "outlet": "China Military Online",
      "date": "2026-09-18",
      "rung": 8
    }
  },
  "trail": {
    "trail": {
      "since": "2026-08-22",
      "until": "2026-09-20",
      "capped": false,
      "rows": [
        {
          "target": "USA",
          "dots": [
            {
              "key": "USA|2026-08-27",
              "target": "USA",
              "day": "2026-08-27",
              "rung": 6,
              "zh": "坚决反对",
              "en": "resolute opposition",
              "reports": 4,
              "originals": 2,
              "newHigh": false,
              "eventId": null,
              "evidence": [
                {
                  "title": "美声称司法部、美联储等机构遭“中国黑客”攻击，中方严词驳斥：坚决反对并依法打击一切形式的网络攻击",
                  "outlet": "Sina",
                  "url": "#0",
                  "publishedAt": "2026-08-27T02:54:00.000Z",
                  "rung": 6,
                  "eventId": null
                },
                {
                  "title": "外交部：中方坚决反对并依法打击黑客活动，美方所谓“声明”缺乏实证",
                  "outlet": "Global Times",
                  "url": "#1",
                  "publishedAt": "2026-08-27T07:58:00.000Z",
                  "rung": 6,
                  "eventId": null
                }
              ]
            },
            {
              "key": "USA|2026-09-19",
              "target": "USA",
              "day": "2026-09-19",
              "rung": 6,
              "zh": "坚决反对",
              "en": "resolute opposition",
              "reports": 1,
              "originals": 1,
              "newHigh": false,
              "eventId": null,
              "evidence": [
                {
                  "title": "美国再度制裁俄伊中方坚决反对并保留反制权利",
                  "outlet": "VanPeople",
                  "url": "#0",
                  "publishedAt": "2026-09-19T23:35:39.000Z",
                  "rung": 6,
                  "eventId": null
                }
              ]
            }
          ]
        },
        {
          "target": "JPN",
          "dots": [
            {
              "key": "JPN|2026-09-09",
              "target": "JPN",
              "day": "2026-09-09",
              "rung": 8,
              "zh": "强烈抗议",
              "en": "strong protest",
              "reports": 1,
              "originals": 1,
              "newHigh": false,
              "eventId": null,
              "evidence": [
                {
                  "title": "中方强烈谴责日方涉靖国神社消极动向，已向日方提出严正交涉、强烈抗议",
                  "outlet": "Sohu",
                  "url": "#0",
                  "publishedAt": "2026-09-09T12:18:01.000Z",
                  "rung": 8,
                  "eventId": null
                }
              ]
            }
          ]
        },
        {
          "target": "KOR",
          "dots": [
            {
              "key": "KOR|2026-09-03",
              "target": "KOR",
              "day": "2026-09-03",
              "rung": 8,
              "zh": "强烈抗议",
              "en": "strong protest",
              "reports": 3,
              "originals": 2,
              "newHigh": false,
              "eventId": null,
              "evidence": [
                {
                  "title": "中方策展团队因韩国光州双年展涉台错误做法宣布撤展表达强烈抗议，外交部：中方已提出严正交涉，希望韩国政府践行一个中国原则",
                  "outlet": "Sohu",
                  "url": "#0",
                  "publishedAt": "2026-09-03T14:06:06.000Z",
                  "rung": 8,
                  "eventId": null
                },
                {
                  "title": "中方策展团队因韩国光州双年展涉台错误做法宣布撤展，表达强烈抗议，外交部：已向韩方提出严正交涉，希望韩国以实际行动践行一个中国原则",
                  "outlet": "Sohu",
                  "url": "#1",
                  "publishedAt": "2026-09-03T14:31:00.000Z",
                  "rung": 8,
                  "eventId": null
                }
              ]
            },
            {
              "key": "KOR|2026-09-04",
              "target": "KOR",
              "day": "2026-09-04",
              "rung": 8,
              "zh": "强烈抗议",
              "en": "strong protest",
              "reports": 1,
              "originals": 1,
              "newHigh": false,
              "eventId": null,
              "evidence": [
                {
                  "title": "韩国光州双年展出现严重涉台错误，多次沟通无果后中方集体撤展以示强烈抗议！外交部表示，已向韩方提出严正交涉……",
                  "outlet": "Tencent QQ News",
                  "url": "#0",
                  "publishedAt": "2026-09-04T04:07:00.000Z",
                  "rung": 8,
                  "eventId": null
                }
              ]
            }
          ]
        },
        {
          "target": "PHL",
          "dots": [
            {
              "key": "PHL|2026-09-02",
              "target": "PHL",
              "day": "2026-09-02",
              "rung": 4,
              "zh": "严正交涉",
              "en": "makes solemn representations",
              "reports": 1,
              "originals": 1,
              "newHigh": false,
              "eventId": null,
              "evidence": [
                {
                  "title": "中国严正交涉！菲律宾公然耍无赖，海警一招出手直接击碎菲方妄想",
                  "outlet": "NetEase",
                  "url": "#0",
                  "publishedAt": "2026-09-02T09:48:53.000Z",
                  "rung": 4,
                  "eventId": null
                }
              ]
            }
          ]
        }
      ],
      "notStated": [
        {
          "key": "none|2026-08-25",
          "target": null,
          "day": "2026-08-25",
          "rung": 12,
          "zh": "一切必要措施",
          "en": "all necessary measures",
          "reports": 1,
          "originals": 1,
          "newHigh": false,
          "eventId": null,
          "evidence": [
            {
              "title": "美国财政部长贝森特称对不参与制裁伊朗的国家可能采取反制措施，外交部：中方将采取一切必要措施，坚定维护自身权益",
              "outlet": "川观新闻",
              "url": "#0",
              "publishedAt": "2026-08-25T12:18:00.000Z",
              "rung": 12,
              "eventId": null
            }
          ]
        },
        {
          "key": "none|2026-09-04",
          "target": null,
          "day": "2026-09-04",
          "rung": 8,
          "zh": "强烈抗议",
          "en": "strong protest",
          "reports": 1,
          "originals": 1,
          "newHigh": false,
          "eventId": null,
          "evidence": [
            {
              "title": "韩国光州双年展批准台湾地区以“台湾馆”的名称参展 中国大陆强烈抗议并撤展",
              "outlet": "东盟头条",
              "url": "#0",
              "publishedAt": "2026-09-04T01:36:34.000Z",
              "rung": 8,
              "eventId": null
            }
          ]
        },
        {
          "key": "none|2026-09-11",
          "target": null,
          "day": "2026-09-11",
          "rung": 6,
          "zh": "坚决反对",
          "en": "resolute opposition",
          "reports": 1,
          "originals": 1,
          "newHigh": false,
          "eventId": null,
          "evidence": [
            {
              "title": "Anthropic发布154页人工智能滥用报告含多领域涉华案例 北京：坚决反对攻击抹黑",
              "outlet": "RFI",
              "url": "#0",
              "publishedAt": "2026-09-11T13:20:25.000Z",
              "rung": 6,
              "eventId": null
            }
          ]
        },
        {
          "key": "none|2026-09-14",
          "target": null,
          "day": "2026-09-14",
          "rung": 6,
          "zh": "坚决反对",
          "en": "resolute opposition",
          "reports": 2,
          "originals": 2,
          "newHigh": false,
          "eventId": null,
          "evidence": [
            {
              "title": "台湾副总统萧美琴：“即使处境再困难，台湾都将继续勇敢走出与世界同行的路”",
              "outlet": "VOA Chinese",
              "url": "#0",
              "publishedAt": "2026-09-14T22:24:33.000Z",
              "rung": 6,
              "eventId": null
            },
            {
              "title": "萧美琴闪电访意欧盟退出论坛 中方严正交涉",
              "outlet": "茉莉花新闻网",
              "url": "#1",
              "publishedAt": "2026-09-14T14:24:33.000Z",
              "rung": 4,
              "eventId": null
            }
          ]
        }
      ],
      "dots": 10
    }
  },
  "dyad": {
    "aName": "China",
    "bName": "United States",
    "score": 99,
    "series": [
      {
        "date": "2026-06-23",
        "value": 0
      },
      {
        "date": "2026-06-24",
        "value": 0
      },
      {
        "date": "2026-06-25",
        "value": 0
      },
      {
        "date": "2026-06-26",
        "value": 0
      },
      {
        "date": "2026-06-27",
        "value": 0
      },
      {
        "date": "2026-06-28",
        "value": 0
      },
      {
        "date": "2026-06-29",
        "value": 0
      },
      {
        "date": "2026-06-30",
        "value": 0
      },
      {
        "date": "2026-07-01",
        "value": 0
      },
      {
        "date": "2026-07-02",
        "value": 0
      },
      {
        "date": "2026-07-03",
        "value": 0
      },
      {
        "date": "2026-07-04",
        "value": 0
      },
      {
        "date": "2026-07-05",
        "value": 0
      },
      {
        "date": "2026-07-06",
        "value": 0
      },
      {
        "date": "2026-07-07",
        "value": 0
      },
      {
        "date": "2026-07-08",
        "value": 0
      },
      {
        "date": "2026-07-09",
        "value": 0
      },
      {
        "date": "2026-07-10",
        "value": 0
      },
      {
        "date": "2026-07-11",
        "value": 0
      },
      {
        "date": "2026-07-12",
        "value": 0
      },
      {
        "date": "2026-07-13",
        "value": 0
      },
      {
        "date": "2026-07-14",
        "value": 0
      },
      {
        "date": "2026-07-15",
        "value": 0
      },
      {
        "date": "2026-07-16",
        "value": 0
      },
      {
        "date": "2026-07-17",
        "value": 0
      },
      {
        "date": "2026-07-18",
        "value": 0
      },
      {
        "date": "2026-07-19",
        "value": 0
      },
      {
        "date": "2026-07-20",
        "value": 0
      },
      {
        "date": "2026-07-21",
        "value": 0
      },
      {
        "date": "2026-07-22",
        "value": 0
      },
      {
        "date": "2026-07-23",
        "value": 0
      },
      {
        "date": "2026-07-24",
        "value": 0
      },
      {
        "date": "2026-07-25",
        "value": 0
      },
      {
        "date": "2026-07-26",
        "value": 0
      },
      {
        "date": "2026-07-27",
        "value": 0
      },
      {
        "date": "2026-07-28",
        "value": 0
      },
      {
        "date": "2026-07-29",
        "value": 0
      },
      {
        "date": "2026-07-30",
        "value": 0
      },
      {
        "date": "2026-07-31",
        "value": 0
      },
      {
        "date": "2026-08-01",
        "value": 0
      },
      {
        "date": "2026-08-02",
        "value": 0
      },
      {
        "date": "2026-08-03",
        "value": 0
      },
      {
        "date": "2026-08-04",
        "value": 0
      },
      {
        "date": "2026-08-05",
        "value": 0
      },
      {
        "date": "2026-08-06",
        "value": 0
      },
      {
        "date": "2026-08-07",
        "value": 0
      },
      {
        "date": "2026-08-08",
        "value": 0
      },
      {
        "date": "2026-08-09",
        "value": 0
      },
      {
        "date": "2026-08-10",
        "value": 0
      },
      {
        "date": "2026-08-11",
        "value": 0
      },
      {
        "date": "2026-08-12",
        "value": 0
      },
      {
        "date": "2026-08-13",
        "value": 0
      },
      {
        "date": "2026-08-14",
        "value": 0
      },
      {
        "date": "2026-08-15",
        "value": 0
      },
      {
        "date": "2026-08-16",
        "value": 0
      },
      {
        "date": "2026-08-17",
        "value": 0
      },
      {
        "date": "2026-08-18",
        "value": 0
      },
      {
        "date": "2026-08-19",
        "value": 0
      },
      {
        "date": "2026-08-20",
        "value": 0
      },
      {
        "date": "2026-08-21",
        "value": 0
      },
      {
        "date": "2026-08-22",
        "value": 0
      },
      {
        "date": "2026-08-23",
        "value": 0
      },
      {
        "date": "2026-08-24",
        "value": 6
      },
      {
        "date": "2026-08-25",
        "value": 78
      },
      {
        "date": "2026-08-26",
        "value": 22
      },
      {
        "date": "2026-08-27",
        "value": 48
      },
      {
        "date": "2026-08-28",
        "value": 81
      },
      {
        "date": "2026-08-29",
        "value": 48
      },
      {
        "date": "2026-08-30",
        "value": 32
      },
      {
        "date": "2026-08-31",
        "value": 65
      },
      {
        "date": "2026-09-01",
        "value": 64
      },
      {
        "date": "2026-09-02",
        "value": 73
      },
      {
        "date": "2026-09-03",
        "value": 72
      },
      {
        "date": "2026-09-04",
        "value": 74
      },
      {
        "date": "2026-09-05",
        "value": 64
      },
      {
        "date": "2026-09-06",
        "value": 38
      },
      {
        "date": "2026-09-07",
        "value": 62
      },
      {
        "date": "2026-09-08",
        "value": 29
      },
      {
        "date": "2026-09-09",
        "value": 68
      },
      {
        "date": "2026-09-10",
        "value": 37
      },
      {
        "date": "2026-09-11",
        "value": 71
      },
      {
        "date": "2026-09-12",
        "value": 26
      },
      {
        "date": "2026-09-13",
        "value": 21
      },
      {
        "date": "2026-09-14",
        "value": 38
      },
      {
        "date": "2026-09-15",
        "value": 44
      },
      {
        "date": "2026-09-16",
        "value": 66
      },
      {
        "date": "2026-09-17",
        "value": 71
      },
      {
        "date": "2026-09-18",
        "value": 60
      },
      {
        "date": "2026-09-19",
        "value": 86
      },
      {
        "date": "2026-09-20",
        "value": 47
      }
    ],
    "markers": [
      {
        "date": "2026-09-19",
        "label": "美国再度制裁俄伊中方坚决反对并保留反制权利"
      },
      {
        "date": "2026-09-18",
        "label": "Bae, Kim & Lee and Reed Smith host Korea-US seminar on chip export controls - CHOSUNBIZ"
      },
      {
        "date": "2026-09-19",
        "label": "美签署对俄制裁法案 中国商务部回应"
      },
      {
        "date": "2026-09-20",
        "label": "Trump signs Russia sanctions bill that opens China, India to tariffs"
      },
      {
        "date": "2026-09-11",
        "label": "China's Huawei heads to trial in US over sanctions and trade secrets"
      },
      {
        "date": "2026-09-19",
        "label": "特朗普和习近平会晤 台湾和对台军售或再成焦点"
      },
      {
        "date": "2026-09-20",
        "label": "Philippines says China Coast Guard ship rammed its boat in South China Sea"
      },
      {
        "date": "2026-09-17",
        "label": "India faces 100% tariff threat over Russian oil after US House vote"
      }
    ]
  },
  "alert": {
    "label": "United States",
    "subject": "Kautilya — United States moved to rung 6",
    "text": "A file you watch has moved up the PRC official escalation ladder.\n\nUnited States: rung 6\n  坚决反对 — resolute opposition\n  美国再度制裁俄伊中方坚决反对并保留反制权利\n  https://kautilya.example/events/7ad7e95b25c49d12\n\nMovement up the ladder on a given file matters more than raw volume anywhere on it.\nThis is a corroboration and provenance reading, not a determination of truth.\n\nTurn these off in your account: https://kautilya.example/account"
  }
};
