/**
 * Capture the demo tour's fallback examples from the current corpus.
 *
 *   npm run demo:capture
 *
 * The tour shows today's real examples and falls back to these when today has none that fit, each
 * labelled with the date it was captured. They are GENERATED, never typed: a fallback somebody wrote
 * by hand would be the fabricated example this product refuses to show. If any chapter has no real
 * example in the corpus right now, nothing is written.
 *
 * The file is tracked and published, so the alert digest is rendered with the placeholder origin and
 * the output is checked for the real one before it is written.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { gatherDemoInput } from '@/lib/demo/gather';
import { PLACEHOLDER_ORIGIN } from '@/lib/demo/alert';
import {
  selectAlert, selectDyad, selectEvent, selectLadder, selectLanguage, selectTrail,
} from '@/lib/demo/select';
import type { TrailData } from '@/lib/demo/types';
import type { TrailDot } from '@/lib/verify/trail';

const input = { ...gatherDemoInput({ enforced: false, mode: 'closed', freeLimit: 5 }), origin: PLACEHOLDER_ORIGIN };

const picks = {
  language: selectLanguage(input),
  event: selectEvent(input),
  ladder: selectLadder(input),
  trail: selectTrail(input),
  dyad: selectDyad(input),
  alert: selectAlert(input),
};

const missing = Object.entries(picks).filter(([, v]) => v === null).map(([k]) => k);
if (missing.length) {
  console.error(`No real example in the corpus today for: ${missing.join(', ')}. Nothing written.`);
  process.exit(1);
}

/**
 * The file is tracked and published, and captured data is headlines and outlets only — no link into a
 * corpus that will have moved on. The trail arrives carrying each evidence article's public URL and
 * the corpus id of every event, so both are dropped here. A url becomes `#<index>` rather than a blank
 * because LadderTrail keys its evidence rows by `${dot.key}|${url}`, and two blank urls in one dot
 * would collide. Immutable: the object the selector returned is left as it was.
 */
function withoutLinks(data: TrailData | null): TrailData | null {
  if (!data) return data;
  const dot = (d: TrailDot): TrailDot => ({
    ...d,
    eventId: null,
    evidence: d.evidence.map((e, i) => ({ ...e, eventId: null, url: `#${i}` })),
  });
  const { trail } = data;
  return {
    ...data,
    trail: { ...trail, rows: trail.rows.map((r) => ({ ...r, dots: r.dots.map(dot) })), notStated: trail.notStated.map(dot) },
  };
}

const capturedOn = new Date().toISOString().slice(0, 10);
const body = JSON.stringify({ capturedOn, ...picks, trail: withoutLinks(picks.trail) }, null, 2);

/**
 * Hostnames that must never reach a published file. Discovered at run time — the configured origin,
 * and the domain of every address or URL in .env.local — rather than written here, because THIS file
 * is tracked and published too, and spelling the domain out in the guard would defeat the guard.
 */
function privateHosts(): string[] {
  const env = existsSync('.env.local') ? readFileSync('.env.local', 'utf8') : '';
  const values = [process.env.KAUTILYA_ORIGIN ?? '', ...env.split('\n').map((l) => l.split('=').slice(1).join('='))];
  const hosts = new Set<string>();
  for (const v of values) {
    for (const m of v.matchAll(/(?:@|\/\/)([A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+)/g)) hosts.add(m[1].toLowerCase());
  }
  hosts.delete('kautilya.example');
  return [...hosts];
}

const leaked = privateHosts().filter((h) => body.toLowerCase().includes(h));
if (leaked.length) {
  console.error('The capture contains a private hostname. Refusing to write a file that would be published.');
  process.exit(1);
}

writeFileSync('data/demo-fallbacks.ts', [
  `// Generated by \`npm run demo:capture\` on ${capturedOn}. Do not edit by hand.`,
  '// Real examples captured from the corpus, used by the demo tour when a live one is missing.',
  "import type { Fallbacks } from '@/lib/demo/types';",
  '',
  `export const FALLBACKS: Fallbacks = ${body};`,
  '',
].join('\n'));

console.log(`Wrote data/demo-fallbacks.ts (captured ${capturedOn}): ${Object.keys(picks).join(', ')}`);
