'use strict';
const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const KitEmit = require('../src/shared/kit-emit.js');
const KitThemes = require('../src/shared/kit-themes.js');
const KitRender = require('../src/shared/kit-render.js');
const KitPacks = require('../src/shared/kit-packs.js');
const Themes = require('../src/renderer/js/themes.js');

const ESC = String.fromCharCode(27);
const BACKTICK = String.fromCharCode(96);
const TOKYO = Themes.THEMES['Tokyo Night'];
const OPTIONS = { ui: TOKYO.ui, xterm: TOKYO.xterm, glyphs: 'plain' };

function available(shell) {
  try {
    execFileSync(shell, ['-c', 'exit 0'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

const SHELLS = ['bash', 'zsh'].filter(available);

function emit(dialect, theme, packs, options) {
  return KitEmit.emit(
    theme || KitThemes.THEMES.classic,
    packs || [],
    dialect,
    Object.assign({}, OPTIONS, options || {})
  );
}

/* ------------------------------------------------------------- structure */

test('an unknown dialect produces nothing rather than a guess', () => {
  assert.strictEqual(KitEmit.emit(KitThemes.THEMES.plain, [], 'fish', OPTIONS), '');
  assert.strictEqual(KitEmit.emit(KitThemes.THEMES.plain, [], '', OPTIONS), '');
});

test('an unsalvageable theme produces nothing rather than broken script', () => {
  for (const dialect of KitEmit.DIALECTS) {
    assert.strictEqual(KitEmit.emit(null, [], dialect, OPTIONS), '');
    assert.strictEqual(KitEmit.emit({ name: 'a b', segments: [] }, [], dialect, OPTIONS), '');
  }
});

test('every dialect emits something for every built-in theme', () => {
  for (const dialect of KitEmit.DIALECTS) {
    for (const name of KitThemes.themeNames()) {
      const text = emit(dialect, KitThemes.THEMES[name]);
      assert.ok(text.length > 0, dialect + ' ' + name);
      assert.match(text, /Generated by Josh/, dialect + ' ' + name);
    }
  }
});

/* ------------------------------------------- the markers that matter most */

test('zsh wraps every escape in percent-brace pairs', () => {
  const text = emit('zsh');
  assert.match(text, /%\{\$__josh_c_accent%\}/);
  assert.match(text, /%\{\$__josh_c_reset%\}/);
  assert.strictEqual(text.includes('\\['), false, 'a bash marker leaked into zsh');
});

test('bash wraps every escape in backslash-bracket pairs', () => {
  const text = emit('bash');
  assert.ok(text.includes('\\[$__josh_c_accent\\]'), 'missing bash marker');
  assert.ok(text.includes('\\[$__josh_c_reset\\]'), 'missing bash reset marker');
  assert.strictEqual(text.includes('%{'), false, 'a zsh marker leaked into bash');
});

test('pwsh carries neither marker, because PSReadLine measures VT itself', () => {
  const text = emit('pwsh');
  assert.strictEqual(text.includes('%{'), false);
  assert.strictEqual(text.includes('\\['), false);
});

test('every colour a theme uses is declared once, as a real escape byte', () => {
  for (const dialect of ['zsh', 'bash']) {
    const text = emit(dialect);
    // ANSI-C quoting, so the shell turns this into escape bytes at assignment.
    assert.ok(
      text.includes("__josh_c_accent=$'\\033[38;2;122;162;247m'"),
      dialect + ' accent declaration'
    );
    assert.ok(text.includes("__josh_c_reset=$'\\033[0m'"), dialect + ' reset declaration');
  }
});

test('a colour comes from the theme it was given, not a hardcoded palette', () => {
  const other = Themes.THEMES.Dracula;
  const text = emit('zsh', null, null, { ui: other.ui, xterm: other.xterm });
  assert.ok(text.includes(KitEmit.colourEscape(other.ui.accent, 'zsh')), 'accent');
  assert.strictEqual(text.includes(KitEmit.colourEscape(TOKYO.ui.accent, 'zsh')), false);
});

test('pwsh embeds the escape byte directly, having no quoting form to use', () => {
  const text = emit('pwsh');
  assert.ok(text.includes(ESC + '[38;2;'), 'pwsh needs literal escape bytes');
  assert.strictEqual(emit('zsh').includes(ESC), false, 'no raw escape byte in a POSIX file');
  assert.strictEqual(emit('bash').includes(ESC), false, 'no raw escape byte in a POSIX file');
});

/* ------------------------------------------------------ the percent sign */

test('a percent arriving from a path is doubled for zsh only', () => {
  const doubling = '${__josh_text//\\%/%%}';
  assert.ok(emit('zsh').includes(doubling), 'zsh must double percent');
  assert.strictEqual(emit('bash').includes(doubling), false, 'bash needs no doubling');
  assert.strictEqual(emit('pwsh').includes(doubling), false, 'pwsh needs no doubling');

  // bash does carry %%, but only as the POSIX suffix-removal operator inside
  // the git parser. The distinction is the point: a bare percent scan would
  // pass for the wrong reason.
  assert.strictEqual(emit('bash').includes('__josh_text'), false);
  assert.ok(emit('bash').includes('${__josh_rest%% *}'), 'suffix removal is not doubling');
});

test('a literal glyph is not put through the percent pass, having no need', () => {
  const text = emit('zsh', KitThemes.THEMES.plain);
  // The prompt character is known at emit time and appears inline.
  assert.match(text, /%\{\$__josh_c_accent%\}\$%\{\$__josh_c_reset%\}/);
});

/* ------------------------------------------------------------ pack output */

const NASTY = 'echo $(touch pwned-a) ' + BACKTICK + 'touch pwned-b' + BACKTICK
  + " don't \"quoted\" $HOME";

function nastyPack() {
  return {
    name: 'nasty',
    requires: '',
    aliases: [{ name: 'joshnasty', value: NASTY, requires: '' }],
    functions: [],
  };
}

test('an alias value is single-quoted with its quotes escaped for the dialect', () => {
  const posix = emit('zsh', null, [nastyPack()]);
  assert.ok(posix.includes("'echo $(touch pwned-a) "), 'value must be single-quoted');
  assert.ok(posix.includes("don'\\''t"), 'a single quote must be escaped POSIX-style');

  const pwsh = emit('pwsh', null, [nastyPack()]);
  assert.ok(pwsh.includes("don''t"), 'a single quote must be doubled for PowerShell');
});

test('a pack whose name fails the allowlist contributes nothing at all', () => {
  const bad = {
    name: 'Not A Pack Name',
    requires: '',
    aliases: [{ name: 'joshleak', value: 'echo leaked', requires: '' }],
    functions: [],
  };
  for (const dialect of KitEmit.DIALECTS) {
    const text = emit(dialect, null, [bad]);
    assert.strictEqual(text.includes('joshleak'), false, dialect + ' leaked an alias');
    assert.strictEqual(text.includes('Not A Pack Name'), false, dialect + ' leaked the name');
    assert.strictEqual(text.includes('echo leaked'), false, dialect + ' leaked a value');
  }
});

test('aliases are grouped under a guard for the binary they need', () => {
  const text = emit('zsh', null, [KitPacks.PACKS.git]);
  assert.match(text, /if command -v git >\/dev\/null 2>&1; then/);
  assert.ok(text.includes("__josh_alias 'gst' 'git status'"));
});

test('a binary name that is not a plain word never reaches a guard', () => {
  const pack = {
    name: 'sneaky',
    requires: '',
    aliases: [{ name: 'joshsneak', value: 'echo hi', requires: 'git; touch pwned' }],
    functions: [],
  };
  const text = emit('zsh', null, [pack]);
  assert.strictEqual(text.includes('touch pwned'), false);
  assert.strictEqual(KitEmit.isSafeBinary('git; touch pwned'), false);
  assert.strictEqual(KitEmit.isSafeBinary('git'), true);
});

test('a function is defined only when nothing already answers to its name', () => {
  const text = emit('bash', null, [KitPacks.PACKS.git]);
  assert.match(text, /! command -v gcur >\/dev\/null 2>&1/);
});

/* ---------------------------------------------------------- glyph choice */

test('rich and plain differ, and the git markers come from kit-render', () => {
  const plain = emit('zsh', null, null, { glyphs: 'plain' });
  const rich = emit('zsh', null, null, { glyphs: 'rich' });
  assert.notStrictEqual(plain, rich);
  assert.ok(rich.includes(KitRender.BRANCH_MARK), 'rich carries the branch mark');
  assert.strictEqual(plain.includes(KitRender.BRANCH_MARK), false);
  assert.ok(plain.includes(KitRender.MARKERS.plain.staged + '$JOSH_GIT_STAGED'));
  assert.ok(rich.includes(KitRender.MARKERS.rich.staged + '$JOSH_GIT_STAGED'));
});

test('the elision marker follows the glyph mode', () => {
  assert.ok(emit('zsh', null, null, { glyphs: 'plain' }).includes("JOSH_ELISION='...'"));
  assert.ok(emit('zsh', null, null, { glyphs: 'rich' }).includes("JOSH_ELISION='…'"));
});

/* ----------------------------------------------------- real shells, really */

function runScript(shell, dialect, extra, theme, packs) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'josh-emit-'));
  try {
    const file = path.join(dir, 'kit.sh');
    fs.writeFileSync(file, emit(dialect, theme, packs) + extra, { mode: 0o700 });
    execFileSync(shell, ['-n', file], { stdio: ['pipe', 'pipe', 'pipe'] });
    const stdout = execFileSync(shell, [file], {
      cwd: dir,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return { stdout: stdout, dir: dir };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

/** Everything the shell will actually print, with the non-printing runs cut. */
function visible(prompt, dialect) {
  return dialect === 'zsh'
    ? prompt.replace(/%\{[\s\S]*?%\}/g, '')
    : prompt.replace(/\\\[[\s\S]*?\\\]/g, '');
}

for (const shell of SHELLS) {
  const dialect = shell;

  test(shell + ': the generated script parses and builds a prompt', () => {
    const extra = '\n__josh_prompt\nprintf "P<%s>\\n" "$'
      + (dialect === 'zsh' ? 'PROMPT' : 'PS1') + '"\n';
    const got = runScript(shell, dialect, extra);
    const match = got.stdout.match(/P<([\s\S]*)>/);
    assert.ok(match, 'no prompt was printed: ' + JSON.stringify(got.stdout));
    assert.ok(match[1].length > 0, 'the prompt came out empty');
  });

  test(shell + ': every escape byte lands inside a non-printing marker', () => {
    const extra = '\n__josh_prompt\nprintf "P<%s>\\n" "$'
      + (dialect === 'zsh' ? 'PROMPT' : 'PS1') + '"\n';
    const got = runScript(shell, dialect, extra);
    const prompt = got.stdout.match(/P<([\s\S]*)>/)[1];

    assert.ok(prompt.includes(ESC), 'the prompt should be coloured at all');
    assert.strictEqual(
      visible(prompt, dialect).includes(ESC),
      false,
      'an escape byte escaped its marker, so the shell will miscount the width'
    );
  });

  test(shell + ': the visible prompt ends in the theme prompt character', () => {
    const extra = '\n__josh_prompt\nprintf "P<%s>\\n" "$'
      + (dialect === 'zsh' ? 'PROMPT' : 'PS1') + '"\n';
    const got = runScript(shell, dialect, extra, KitThemes.THEMES.plain);
    const prompt = got.stdout.match(/P<([\s\S]*)>/)[1];
    assert.match(visible(prompt, dialect), /\$$/);
  });

  test(shell + ': a nasty alias value round-trips inertly', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'josh-emit-'));
    try {
      const file = path.join(dir, 'kit.sh');
      fs.writeFileSync(file, emit(dialect, null, [nastyPack()]), { mode: 0o700 });
      execFileSync(shell, [file], { cwd: dir, stdio: ['pipe', 'pipe', 'pipe'] });
      assert.strictEqual(fs.existsSync(path.join(dir, 'pwned-a')), false, 'command substitution ran');
      assert.strictEqual(fs.existsSync(path.join(dir, 'pwned-b')), false, 'backticks ran');
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  test(shell + ': the shipped packs install without error', () => {
    const packs = KitPacks.selectPacks(['git', 'core', 'dev', 'systems']);
    const extra = '\nprintf "ok=%s\\n" "$?"\n';
    const got = runScript(shell, dialect, extra, null, packs);
    assert.strictEqual(got.stdout.trim(), 'ok=0');
  });

  test(shell + ': a multiline theme puts the prompt character on its own line', () => {
    const extra = '\n__josh_prompt\nprintf "P<%s>\\n" "$'
      + (dialect === 'zsh' ? 'PROMPT' : 'PS1') + '"\n';
    const got = runScript(shell, dialect, extra, KitThemes.THEMES.stack);
    const prompt = got.stdout.match(/P<([\s\S]*)>/)[1];
    const shown = visible(prompt, dialect);
    assert.ok(shown.includes('\n') || shown.includes('\\n'), 'no line break was emitted');
  });
}
