'use strict';
const test = require('node:test');
const assert = require('node:assert');
const I = require('../src/renderer/js/trace-interp.js');

const NL = String.fromCharCode(10);
function src() {
  return Array.prototype.slice.call(arguments).join(NL);
}

/**
 * End-to-end programs. Each asserts either exact output or an exact diagnostic
 * code. A failure here points at an interaction between modules that the unit
 * tests missed, which is the whole reason the corpus exists: fix the modules,
 * not the corpus, unless a program is genuinely wrong C.
 */
const PROGRAMS = [
  // --- Basics ------------------------------------------------------------
  { name: 'arithmetic and precedence',
    source: 'int main(void) { printf("%d", 2 + 3 * 4); return 0; }',
    output: '14' },
  { name: 'integer division truncates toward zero',
    source: 'int main(void) { printf("%d %d", 7 / 2, -7 / 2); return 0; }',
    output: '3 -3' },
  { name: 'modulo follows the sign of the dividend',
    source: 'int main(void) { printf("%d %d", 7 % 3, -7 % 3); return 0; }',
    output: '1 -1' },
  { name: 'char arithmetic produces letters',
    source: src('int main(void) {', "  char c = 'a';", '  printf("%c", c + 1);',
      '  return 0;', '}'),
    output: 'b' },
  { name: 'sizeof reports real sizes including padding',
    source: src('struct S { char c; int i; };', 'int main(void) {',
      '  printf("%d %d %d", sizeof(int), sizeof(char), sizeof(struct S));',
      '  return 0;', '}'),
    output: '4 1 8' },
  { name: 'a cast to int truncates toward zero',
    source: 'int main(void) { printf("%d %d", (int)3.9, (int)-3.9); return 0; }',
    output: '3 -3' },
  { name: 'double arithmetic keeps its fraction',
    source: 'int main(void) { printf("%.2f", 7.0 / 2); return 0; }',
    output: '3.50' },
  { name: 'comparison yields one or zero',
    source: 'int main(void) { printf("%d%d", 3 > 2, 2 > 3); return 0; }',
    output: '10' },
  { name: 'logical and short-circuits, so the call never happens',
    source: src('int calls = 0;', 'int bump(void) { calls = calls + 1; return 1; }',
      'int main(void) { if (0 && bump()) { } printf("%d", calls); return 0; }'),
    output: '0' },
  { name: 'bitwise operators',
    source: 'int main(void) { printf("%d %d %d", 6 & 3, 6 | 3, 6 ^ 3); return 0; }',
    output: '2 7 5' },

  // --- Control flow ------------------------------------------------------
  { name: 'fizzbuzz to fifteen',
    source: src('int main(void) {', '  for (int i = 1; i <= 15; i++) {',
      '    if (i % 15 == 0) printf("FB");',
      '    else if (i % 3 == 0) printf("F");',
      '    else if (i % 5 == 0) printf("B");',
      '    else printf("%d", i);', '  }', '  return 0;', '}'),
    output: '12F4BF78FB11F1314FB' },
  { name: 'switch falls through until break',
    source: src('int main(void) {', '  int n = 0;', '  switch (1) {',
      '    case 1: n = n + 1;', '    case 2: n = n + 10; break;',
      '    case 3: n = n + 100;', '  }', '  printf("%d", n);', '  return 0;', '}'),
    output: '11' },
  { name: 'nested loops build a triangle',
    source: src('int main(void) {', '  for (int i = 1; i <= 3; i++) {',
      '    for (int j = 0; j < i; j++) printf("*");', '    printf("|");', '  }',
      '  return 0;', '}'),
    output: '*|**|***|' },
  { name: 'while counts down',
    source: src('int main(void) {', '  int n = 3;',
      '  while (n > 0) { printf("%d", n); n = n - 1; }', '  return 0;', '}'),
    output: '321' },
  { name: 'do-while runs at least once',
    source: src('int main(void) {', '  int n = 0;',
      '  do { printf("x"); n = n + 1; } while (n < 0);', '  return 0;', '}'),
    output: 'x' },
  { name: 'break leaves the loop early',
    source: src('int main(void) {', '  for (int i = 0; i < 5; i++) {',
      '    if (i == 3) break;', '    printf("%d", i);', '  }', '  return 0;', '}'),
    output: '012' },
  { name: 'continue skips the even numbers',
    source: src('int main(void) {', '  for (int i = 0; i < 5; i++) {',
      '    if (i % 2 == 0) continue;', '    printf("%d", i);', '  }',
      '  return 0;', '}'),
    output: '13' },
  { name: 'a dangling else binds to the nearest if',
    source: src('int classify(int n) {', '  if (n > 0)',
      '    if (n > 10) return 2;', '    else return 1;', '  return 0;', '}',
      'int main(void) {',
      '  printf("%d%d%d", classify(20), classify(5), classify(-1));',
      '  return 0;', '}'),
    output: '210' },
  { name: 'switch on a character',
    source: src('int main(void) {', "  char g = 'B';", '  switch (g) {',
      '    case 65: printf("top"); break;', '    case 66: printf("mid"); break;',
      '    default: printf("low");', '  }', '  return 0;', '}'),
    output: 'mid' },
  { name: 'sum one to ten',
    source: src('int main(void) {', '  int s = 0;',
      '  for (int i = 1; i <= 10; i++) s = s + i;', '  printf("%d", s);',
      '  return 0;', '}'),
    output: '55' },
  { name: 'an else-if ladder',
    source: src('int main(void) {', '  int score = 73;',
      '  if (score >= 90) printf("A");', '  else if (score >= 80) printf("B");',
      '  else if (score >= 70) printf("C");', '  else printf("D");',
      '  return 0;', '}'),
    output: 'C' },
  { name: 'an endless loop broken from inside',
    source: src('int main(void) {', '  int i = 0;',
      '  while (1) { i = i + 1; if (i == 4) break; }', '  printf("%d", i);',
      '  return 0;', '}'),
    output: '4' },

  // --- Functions ---------------------------------------------------------
  { name: 'recursion computes a factorial',
    source: src('int fact(int n) {', '  if (n <= 1) return 1;',
      '  return n * fact(n - 1);', '}',
      'int main(void) { printf("%d", fact(6)); return 0; }'),
    output: '720' },
  { name: 'swap through pointers changes the caller',
    source: src('void swap(int *a, int *b) {', '  int t = *a; *a = *b; *b = t;', '}',
      'int main(void) {', '  int x = 1; int y = 2;', '  swap(&x, &y);',
      '  printf("%d%d", x, y);', '  return 0;', '}'),
    output: '21' },
  { name: 'mutual recursion, with no prototypes needed',
    source: src('int isEven(int n) { if (n == 0) return 1; return isOdd(n - 1); }',
      'int isOdd(int n) { if (n == 0) return 0; return isEven(n - 1); }',
      'int main(void) { printf("%d%d", isEven(4), isOdd(4)); return 0; }'),
    output: '10' },
  { name: 'a void function changing a global',
    source: src('int total = 0;', 'void add(int n) { total = total + n; }',
      'int main(void) { add(3); add(4); printf("%d", total); return 0; }'),
    output: '7' },
  { name: 'an early return short-circuits the rest',
    source: src('int firstNegative(int a, int b, int c) {',
      '  if (a < 0) return a;', '  if (b < 0) return b;', '  if (c < 0) return c;',
      '  return 0;', '}',
      'int main(void) { printf("%d", firstNegative(3, -2, 5)); return 0; }'),
    output: '-2' },
  { name: 'one function called twice',
    source: src('int square(int n) { return n * n; }',
      'int main(void) { printf("%d %d", square(3), square(4)); return 0; }'),
    output: '9 16' },
  { name: 'fibonacci through many frames',
    source: src('int fib(int n) { if (n < 2) return n; return fib(n - 1) + fib(n - 2); }',
      'int main(void) { printf("%d", fib(10)); return 0; }'),
    output: '55' },
  { name: 'an array argument decays to a pointer',
    source: src('int sum(int *a, int n) {', '  int t = 0;',
      '  for (int i = 0; i < n; i++) t = t + a[i];', '  return t;', '}',
      'int main(void) {', '  int v[4] = {1, 2, 3, 4};',
      '  printf("%d", sum(v, 4));', '  return 0;', '}'),
    output: '10' },
  { name: 'a function modifies the caller array through a pointer',
    source: src('void doubleAll(int *a, int n) {',
      '  for (int i = 0; i < n; i++) a[i] = a[i] * 2;', '}',
      'int main(void) {', '  int v[3] = {1, 2, 3};', '  doubleAll(v, 3);',
      '  printf("%d%d%d", v[0], v[1], v[2]);', '  return 0;', '}'),
    output: '246' },
  { name: 'gcd by recursion',
    source: src('int gcd(int a, int b) { if (b == 0) return a; return gcd(b, a % b); }',
      'int main(void) { printf("%d", gcd(48, 18)); return 0; }'),
    output: '6' },

  // --- Arrays and strings ------------------------------------------------
  { name: 'sum an array',
    source: src('int main(void) {', '  int a[5] = {1, 2, 3, 4, 5};', '  int total = 0;',
      '  for (int i = 0; i < 5; i++) total = total + a[i];',
      '  printf("%d", total);', '  return 0;', '}'),
    output: '15' },
  { name: 'reverse a string in place',
    source: src('int main(void) {', '  char s[6] = "abcde";', '  int n = strlen(s);',
      '  for (int i = 0; i < n / 2; i++) {',
      '    char t = s[i]; s[i] = s[n - 1 - i]; s[n - 1 - i] = t;', '  }',
      '  printf("%s", s);', '  return 0;', '}'),
    output: 'edcba' },
  { name: 'a two-dimensional array',
    source: src('int main(void) {', '  int g[2][3];',
      '  for (int i = 0; i < 2; i++)',
      '    for (int j = 0; j < 3; j++) g[i][j] = i * 3 + j;',
      '  printf("%d%d", g[0][2], g[1][0]);', '  return 0;', '}'),
    output: '23' },
  { name: 'find the largest element',
    source: src('int main(void) {', '  int a[5] = {3, 9, 2, 7, 5};', '  int best = a[0];',
      '  for (int i = 1; i < 5; i++) if (a[i] > best) best = a[i];',
      '  printf("%d", best);', '  return 0;', '}'),
    output: '9' },
  { name: 'count characters up to the terminator',
    source: src('int main(void) {', '  char s[6] = "hello";', '  int n = 0;',
      '  for (int i = 0; s[i] != 0; i++) n = n + 1;', '  printf("%d", n);',
      '  return 0;', '}'),
    output: '5' },
  { name: 'copy a string with strcpy',
    source: src('int main(void) {', '  char dst[6];', '  strcpy(dst, "hello");',
      '  printf("%s", dst);', '  return 0;', '}'),
    output: 'hello' },
  { name: 'compare strings',
    source: 'int main(void) { printf("%d", strcmp("abc", "abc") == 0); return 0; }',
    output: '1' },
  { name: 'build a string with strcat',
    source: src('int main(void) {', '  char buf[12];', '  strcpy(buf, "hello ");',
      '  strcat(buf, "world");', '  printf("%s", buf);', '  return 0;', '}'),
    output: 'hello world' },
  { name: 'a partial initialiser zero-fills the rest',
    source: src('int main(void) {', '  int a[5] = {1, 2};',
      '  printf("%d%d%d", a[0], a[1], a[4]);', '  return 0;', '}'),
    output: '120' },
  { name: 'count the vowels',
    source: src('int main(void) {', '  char s[12] = "hello world";', '  int v = 0;',
      '  for (int i = 0; s[i] != 0; i++) {', '    char c = s[i];',
      "    if (c == 'a' || c == 'e' || c == 'i' || c == 'o' || c == 'u') v = v + 1;",
      '  }', '  printf("%d", v);', '  return 0;', '}'),
    output: '3' },
  { name: 'string length by hand agrees with strlen',
    source: src('int main(void) {', '  char s[4] = "abc";', '  int n = 0;',
      '  while (s[n] != 0) n = n + 1;', '  printf("%d %d", n, strlen(s));',
      '  return 0;', '}'),
    output: '3 3' },
  { name: 'bubble sort',
    source: src('int main(void) {', '  int a[5] = {5, 3, 4, 1, 2};',
      '  for (int i = 0; i < 5; i++) {', '    for (int j = 0; j < 4 - i; j++) {',
      '      if (a[j] > a[j + 1]) {',
      '        int t = a[j]; a[j] = a[j + 1]; a[j + 1] = t;', '      }', '    }',
      '  }', '  for (int i = 0; i < 5; i++) printf("%d", a[i]);', '  return 0;', '}'),
    output: '12345' },

  // --- Pointers ----------------------------------------------------------
  { name: 'walking an array with a pointer',
    source: src('int main(void) {', '  int a[4] = {10, 20, 30, 40};', '  int *p = a;',
      '  printf("%d %d", *p, *(p + 2));', '  return 0;', '}'),
    output: '10 30' },
  { name: 'a[i] and *(a + i) are the same thing',
    source: src('int main(void) {', '  int a[3] = {5, 6, 7};',
      '  if (a[1] == *(a + 1)) printf("same");', '  return 0;', '}'),
    output: 'same' },
  { name: 'a pointer to a pointer',
    source: src('int main(void) {', '  int x = 5;', '  int *p = &x;', '  int **pp = &p;',
      '  printf("%d", **pp);', '  return 0;', '}'),
    output: '5' },
  { name: 'subtracting two pointers counts elements, not bytes',
    source: src('int main(void) {', '  int a[5];', '  int *p = &a[1];', '  int *q = &a[4];',
      '  printf("%d", q - p);', '  return 0;', '}'),
    output: '3' },
  { name: 'a null pointer compares equal to zero',
    source: src('int main(void) {', '  int *p = 0;',
      '  if (p == 0) printf("null"); else printf("not");', '  return 0;', '}'),
    output: 'null' },
  { name: 'setting a caller variable through a pointer parameter',
    source: src('void setToZero(int *p) { *p = 0; }',
      'int main(void) { int x = 5; setToZero(&x); printf("%d", x); return 0; }'),
    output: '0' },
  { name: 'a pointer into the middle of an array',
    source: src('int main(void) {', '  int a[5] = {1, 2, 3, 4, 5};', '  int *p = &a[2];',
      '  printf("%d %d", *p, *(p - 1));', '  return 0;', '}'),
    output: '3 2' },
  { name: 'two string literals',
    source: src('int main(void) {', '  char *a = "hi";', '  char *b = "there";',
      '  printf("%s %s", a, b);', '  return 0;', '}'),
    output: 'hi there' },
  { name: 'an array on the heap',
    source: src('int main(void) {', '  int *a = malloc(12);',
      '  for (int i = 0; i < 3; i++) a[i] = i * i;',
      '  printf("%d%d%d", a[0], a[1], a[2]);', '  free(a);', '  return 0;', '}'),
    output: '014' },
  { name: 'pointers into one array compare in order',
    source: src('int main(void) {', '  int a[3];', '  int *p = a;', '  int *q = &a[2];',
      '  printf("%d", p < q);', '  return 0;', '}'),
    output: '1' },
  { name: 'incrementing a pointer moves it one element',
    source: src('int main(void) {', '  int a[3] = {7, 8, 9};', '  int *p = a;', '  p++;',
      '  printf("%d", *p);', '  return 0;', '}'),
    output: '8' },
  { name: 'returning a pointer to a heap block is fine',
    source: src('int *make(void) { int *p = malloc(4); *p = 9; return p; }',
      'int main(void) { int *q = make(); printf("%d", *q); free(q); return 0; }'),
    output: '9' },

  // --- Structs and enums -------------------------------------------------
  { name: 'a struct through a pointer',
    source: src('struct P { int x; int y; };',
      'int total(struct P *p) { return p->x + p->y; }',
      'int main(void) {', '  struct P p; p.x = 3; p.y = 4;',
      '  printf("%d", total(&p));', '  return 0;', '}'),
    output: '7' },
  { name: 'an array of structs',
    source: src('struct P { int x; int y; };', 'int main(void) {',
      '  struct P pts[2];', '  pts[0].x = 1; pts[0].y = 2;',
      '  pts[1].x = 3; pts[1].y = 4;',
      '  printf("%d", pts[0].x + pts[1].y);', '  return 0;', '}'),
    output: '5' },
  { name: 'a nested struct',
    source: src('struct Inner { int v; };', 'struct Outer { struct Inner i; int w; };',
      'int main(void) {', '  struct Outer o;', '  o.i.v = 3; o.w = 4;',
      '  printf("%d", o.i.v + o.w);', '  return 0;', '}'),
    output: '7' },
  { name: 'enum constants count up from zero',
    source: src('enum Colour { RED, GREEN, BLUE };',
      'int main(void) { printf("%d%d%d", RED, GREEN, BLUE); return 0; }'),
    output: '012' },
  { name: 'an explicit enum value restarts the count',
    source: src('enum E { A = 5, B, C = 10, D };',
      'int main(void) { printf("%d%d%d%d", A, B, C, D); return 0; }'),
    output: '561011' },
  { name: 'a struct member updated in a loop',
    source: src('struct Counter { int n; };', 'int main(void) {',
      '  struct Counter c; c.n = 0;',
      '  for (int i = 0; i < 5; i++) c.n = c.n + i;',
      '  printf("%d", c.n);', '  return 0;', '}'),
    output: '10' },

  // --- The classic mistakes ---------------------------------------------
  { name: 'off by one at the end of an array',
    source: src('int main(void) {', '  int a[5];',
      '  for (int i = 0; i <= 5; i++) a[i] = i;', '  return 0;', '}'),
    code: 'index-out-of-range' },
  { name: 'reading a variable that was never set',
    source: src('int main(void) {', '  int total;',
      '  for (int i = 0; i < 3; i++) total = total + i;',
      '  printf("%d", total);', '  return 0;', '}'),
    code: 'uninitialised-read' },
  { name: 'returning a pointer to a local',
    source: src('int *broken(void) {', '  int local = 42;', '  return &local;', '}',
      'int main(void) {', '  int *p = broken();', '  printf("%d", *p);',
      '  return 0;', '}'),
    code: 'dangling-stack-pointer' },
  { name: 'forgetting to free',
    source: src('int main(void) {', '  int *p = malloc(100);', '  *p = 1;',
      '  return 0;', '}'),
    code: 'memory-leak' },
  { name: 'a buffer with no room for the terminator',
    source: src('int main(void) {', '  char s[5];', '  strcpy(s, "hello");',
      '  return 0;', '}'),
    code: 'out-of-bounds-write' },
  { name: 'dividing by a counter that reached zero',
    source: src('int main(void) {', '  int n = 3;',
      '  while (n >= 0) { printf("%d", 12 / n); n = n - 1; }', '  return 0;', '}'),
    code: 'divide-by-zero' },
  { name: 'a loop whose condition never changes',
    source: src('int main(void) {', '  int i = 0;',
      '  while (i < 10) { printf("x"); }', '  return 0;', '}'),
    code: 'step-limit', maxSteps: 500 },
  { name: 'using memory after freeing it',
    source: src('int main(void) {', '  int *p = malloc(4);', '  *p = 1;', '  free(p);',
      '  printf("%d", *p);', '  return 0;', '}'),
    code: 'use-after-free' },
  { name: 'freeing the same block twice',
    source: src('int main(void) {', '  int *p = malloc(4);', '  free(p);', '  free(p);',
      '  return 0;', '}'),
    code: 'double-free' },
  { name: 'freeing something malloc never gave you',
    source: src('int main(void) {', '  int x = 1;', '  free(&x);', '  return 0;', '}'),
    code: 'free-of-non-heap' },
  { name: 'dereferencing a null pointer',
    source: src('int main(void) {', '  int *p = 0;', '  printf("%d", *p);',
      '  return 0;', '}'),
    code: 'null-dereference' },
  { name: 'a negative array index',
    source: src('int main(void) {', '  int a[3];', '  int i = -1;', '  a[i] = 1;',
      '  return 0;', '}'),
    code: 'negative-index' },
  { name: 'an int that will not hold the answer',
    source: src('int main(void) {', '  int big = 100000;',
      '  printf("%d", big * big);', '  return 0;', '}'),
    code: 'signed-overflow' },
  { name: 'a path through a function with no return',
    source: src('int f(int n) { if (n > 0) return 1; }',
      'int main(void) { return f(-1); }'),
    code: 'missing-return' },
];

function runToEnd(program) {
  const runner = I.createRunner({
    source: program.source,
    stdin: program.stdin || '',
    maxSteps: program.maxSteps || 200000,
  });
  assert.deepStrictEqual(runner.errors, [],
    'should parse cleanly: ' + JSON.stringify(runner.errors));
  let result = null;
  for (let i = 0; i <= (program.maxSteps || 200000) + 2; i += 1) {
    result = runner.step();
    if (result.done) break;
  }
  return { runner: runner, result: result };
}

for (const program of PROGRAMS) {
  test('corpus: ' + program.name, () => {
    const outcome = runToEnd(program);
    const result = outcome.result;

    if (program.code) {
      assert.ok(result.diagnostic, 'expected diagnostic ' + program.code);
      assert.strictEqual(result.diagnostic.code, program.code);
      assert.ok(result.diagnostic.plain.length > 20, 'the explanation must be real');
      assert.ok(result.diagnostic.locations.length > 0, 'and must point somewhere');
    } else {
      assert.strictEqual(result.diagnostic, null,
        result.diagnostic && result.diagnostic.terse);
      assert.strictEqual(outcome.runner.state().output.join(''), program.output);
    }
  });
}

test('the corpus covers every group and is the promised size', () => {
  assert.ok(PROGRAMS.length >= 60, 'got ' + PROGRAMS.length);
  assert.ok(PROGRAMS.filter((p) => p.code).length >= 14, 'one per diagnostic');
  const names = PROGRAMS.map((p) => p.name);
  assert.strictEqual(new Set(names).size, names.length, 'names must be unique');
});

test('every corpus program is deterministic', () => {
  for (const program of PROGRAMS) {
    if (program.code === 'step-limit') continue; // capped, not run to completion
    const outputs = [0, 1].map(function () {
      return runToEnd(program).runner.state().output.join('');
    });
    assert.strictEqual(outputs[0], outputs[1], program.name);
  }
});
